name: Deploy on Push

on:
  push:
    branches:
    - main
  release:
    types:
    - created

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm install && yarn global add @vscode/vsce 

    - name: Check Commit Message
      uses: actions/checkout@v2

    - name: Get Commit Message
      id: commit_message
      run: echo "::set-output name=message::$(git log --format=%B -n 1 $GITHUB_SHA)"
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
       
      run: npm i -g semantic-release @semantic-release/changelog @semantic-release/git  @semantic-release/commit-analyzer conventional-changelog-conventionalcommits && npx semantic-release

    - name: Publish
      uses: JCofman/vscodeaction@master
      env:
       PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
      with:
       args: publish -p $PUBLISHER_TOKEN