name: Deploy on Push

on:
  push:
    branches:
    - master
  release:
    types:
    - created

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4

      with:
        node-version: 20.x
    - run: npm install && yarn global add @vscode/vsce 

    - name: Check Commit Message
      uses: actions/checkout@v2

    - name: Publish Extension
      uses: JCofman/vscodeaction@master
      env:
       PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
      with:
       args: publish -p $PUBLISHER_TOKEN