name: webhook for file trigger

on:
  workflow_dispatch:
  
jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run Node.js script
        run: node .github/workflows/file_edit.js
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
